
# As formatted by dcm2nii and dcm2niix. Name of the DTI file to filter
# out of raw data files. If both protocol files are present then index 0th
# protocol name will be used for further processing.
protocol_names: [
  'xDTImediumiso', 'dti_medium_iso'
]

# Number of gradient directions per DTI volume
n_gradients: 16

#* FULL PATHS TO FOLDERS AND FILES
paths:
  # Main folders in project tree
  root_dir: &root_dir !rootdir # The parent folder
  data_dir: &data_dir !joinpath [*root_dir, data] # Data parent folder
  logs_dir: !joinpath [*root_dir, logs]
  tests_dir: !joinpath [*root_dir, tests]
  config_dir: !joinpath [*root_dir, config] # Configuration folder
  notebooks_dir: !joinpath [*root_dir, notebooks] # notebooks folder
  
log: # logging default settings
  name: dtipLogger # Name of the logger. Name must be same as logging.conf 
  filename: dtip_logs

project_name: dtip
